spring:
  application:
    name: TrycoreDesafioBack
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  show-login-endpoint: true
logging:
  level:
    org.springframework.boot.autoconfigure.liquibase: DEBUG